theme: jekyll-theme-architect

title: [release-notes]
description: [Eclipse GlassFish Server Release Notes, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/release-notes
  download: https://github.com/javaee/release-notes/releases
  #mailinglist: https://javaee.groups.io/g/release-notes
  #javadocs:
  docs: https://javaee.github.io/release-notes
  #faq:

