theme: jekyll-theme-architect

title: [application-development-guide]
description: [Eclipse GlassFish Server Application Development Guide, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/application-development-guide
  download: https://github.com/javaee/application-development-guide/releases
  #mailinglist: https://javaee.groups.io/g/application-development-guide
  #javadocs:
  docs: https://javaee.github.io/application-development-guide
  #faq:

