theme: jekyll-theme-architect

title: [administration-guide]
description: [Eclipse GlassFish Server Administration Guide, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/administration-guide
  download: https://github.com/javaee/administration-guide/releases
  #mailinglist: https://javaee.groups.io/g/administration-guide
  #javadocs:
  docs: https://javaee.github.io/administration-guide
  #faq:

