theme: jekyll-theme-architect

title: [application-deployment-guide]
description: [Eclipse GlassFish Server Application Deployment Guide, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/application-deployment-guide
  download: https://github.com/javaee/application-deployment-guide/releases
  #mailinglist: https://javaee.groups.io/g/application-deployment-guide
  #javadocs:
  docs: https://javaee.github.io/application-deployment-guide
  #faq:

