theme: jekyll-theme-architect

title: [reference-manual]
description: [Eclipse GlassFish Server Reference Manual, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/reference-manual
  download: https://github.com/javaee/reference-manual/releases
  #mailinglist: https://javaee.groups.io/g/reference-manual
  #javadocs:
  docs: https://javaee.github.io/reference-manual
  #faq:

