theme: jekyll-theme-architect

title: [performance-tuning-guide]
description: [Eclipse GlassFish Server Performance Tuning Guide, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/performance-tuning-guide
  download: https://github.com/javaee/performance-tuning-guide/releases
  #mailinglist: https://javaee.groups.io/g/performance-tuning-guide
  #javadocs:
  docs: https://javaee.github.io/performance-tuning-guide
  #faq:

