theme: jekyll-theme-architect

title: [deployment-planning-guide]
description: [Eclipse GlassFish Server Deployment Planning Guide, Release 5.1]

# sidebar links url
links:
  source: https://github.com/javaee/deployment-planning-guide
  download: https://github.com/javaee/deployment-planning-guide/releases
  #mailinglist: https://javaee.groups.io/g/deployment-planning-guide
  #javadocs:
  docs: https://javaee.github.io/deployment-planning-guide
  #faq:

